"""create campaigns table

Revision ID: 15609679eeac
Revises: e22fb6dfb128
Create Date: 2026-09-12 02:56:44.862824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15609679eeac'
down_revision: Union[str, None] = 'e22fb6dfb128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('advertiser_id', sa.Uuid(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'ended', name='campaignstatus'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    # ### end Alembic commands ###
