"""add spent column to campaigns table

Revision ID: 16cece779066
Revises: 598e0e35ee61
Create Date: 2026-09-15 19:44:13.824849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16cece779066'
down_revision: Union[str, None] = '598e0e35ee61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('spent', sa.Numeric(precision=12, scale=4), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'spent')
    # ### end Alembic commands ###
