"""index foreign keys used by analytics queries

Revision ID: 1a820b89a277
Revises: bcaaed4e43e4
Create Date: 2026-09-17 00:42:16.875423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a820b89a277'
down_revision: Union[str, None] = 'bcaaed4e43e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clicks_impression_id'), 'clicks', ['impression_id'], unique=False)
    op.create_index(op.f('ix_conversions_click_id'), 'conversions', ['click_id'], unique=False)
    op.create_index(op.f('ix_impressions_campaign_id'), 'impressions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_impressions_user_id'), 'impressions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_impressions_user_id'), table_name='impressions')
    op.drop_index(op.f('ix_impressions_campaign_id'), table_name='impressions')
    op.drop_index(op.f('ix_conversions_click_id'), table_name='conversions')
    op.drop_index(op.f('ix_clicks_impression_id'), table_name='clicks')
    # ### end Alembic commands ###
