"""add api key hash to advertisers

Revision ID: 2b11a4363bfe
Revises: 67880fcfee6a
Create Date: 2026-09-17 00:36:17.054387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b11a4363bfe'
down_revision: Union[str, None] = '67880fcfee6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisers', sa.Column('api_key_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_advertisers_api_key_hash'), 'advertisers', ['api_key_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertisers_api_key_hash'), table_name='advertisers')
    op.drop_column('advertisers', 'api_key_hash')
    # ### end Alembic commands ###
