"""add targeting_interests join table

Revision ID: 598e0e35ee61
Revises: 7d3a9ab8f204
Create Date: 2026-09-15 15:54:35.286563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598e0e35ee61'
down_revision: Union[str, None] = '7d3a9ab8f204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targeting_interests',
    sa.Column('targeting_id', sa.Uuid(), nullable=False),
    sa.Column('interest_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['targeting_id'], ['audience_targeting.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('targeting_id', 'interest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('targeting_interests')
    # ### end Alembic commands ###
