"""add weight column to user_interests table

Revision ID: 737238877cc4
Revises: f1138f08d1a3
Create Date: 2026-09-16 23:26:29.478978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737238877cc4'
down_revision: Union[str, None] = 'f1138f08d1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interests', sa.Column('weight', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_interests', 'weight')
    # ### end Alembic commands ###
