"""add user, interest, and user_interests tables

Revision ID: 7d3a9ab8f204
Revises: 448fd443d9d2
Create Date: 2026-09-14 11:20:21.622345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7d3a9ab8f204'
down_revision: Union[str, None] = '448fd443d9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('audience_targeting', 'country',
    existing_type=sa.String(),
    type_=sa.String(length=2),
    existing_nullable=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('device_type', postgresql.ENUM('desktop', 'mobile', 'tablet', name='devicetype', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_interests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('interest_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'interest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_interests')
    op.drop_table('users')
    op.drop_table('interests')
    # ### end Alembic commands ###
    op.alter_column('audience_targeting', 'country',
    existing_type=sa.String(length=2),
    type_=sa.String(),
    existing_nullable=True)
