"""add suspicious flag to clicks

Revision ID: bcaaed4e43e4
Revises: 2b11a4363bfe
Create Date: 2026-09-17 00:38:38.698832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcaaed4e43e4'
down_revision: Union[str, None] = '2b11a4363bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('suspicious', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clicks', 'suspicious')
    # ### end Alembic commands ###
