"""drop unused impression indexes after measuring write cost

Revision ID: dcf2afa14820
Revises: 1a820b89a277
Create Date: 2026-09-17 01:01:40.760281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcf2afa14820'
down_revision: Union[str, None] = '1a820b89a277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_impressions_campaign_id', table_name='impressions')
    op.drop_index('ix_impressions_user_id', table_name='impressions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_impressions_user_id', 'impressions', ['user_id'], unique=False)
    op.create_index('ix_impressions_campaign_id', 'impressions', ['campaign_id'], unique=False)
    # ### end Alembic commands ###
