"""add impressions, clicks, and conversions tables

Revision ID: f1138f08d1a3
Revises: 16cece779066
Create Date: 2026-09-15 22:33:56.151845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f1138f08d1a3'
down_revision: Union[str, None] = '16cece779066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impressions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_age', sa.Integer(), nullable=False),
    sa.Column('user_country', sa.String(length=2), nullable=False),
    sa.Column('user_device_type', postgresql.ENUM('desktop', 'mobile', 'tablet', name='devicetype', create_type=False), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clicks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('impression_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['impression_id'], ['impressions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impression_interests',
    sa.Column('impression_id', sa.Uuid(), nullable=False),
    sa.Column('interest_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['impression_id'], ['impressions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('impression_id', 'interest_id')
    )
    op.create_table('conversions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('click_id', sa.Uuid(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['click_id'], ['clicks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversions')
    op.drop_table('impression_interests')
    op.drop_table('clicks')
    op.drop_table('impressions')
    # ### end Alembic commands ###
